### PR TITLE
merge master into coverity_scan to update coverity results

### PR DESCRIPTION
**Pull request by detonin**

### CODE REVIEW

**Comment by stweil** [comment]
Wouldn't it be better (and easier) to reset the `coverity_scan` branch to `master` (instead of merging)?

The last Coverity scan was exactly one year ago and much has changed and improved since that time. Therefore I appreciate the effort to make a new scan.

**Comment by stweil** [comment]
@detonin, @mayeut, what is the status of this pull request? I suggest to close it and reset the `coverity_scan` branch as I have written above.

**Comment by stweil** [comment]
@rouault, what is the use of this pull request at all? It has conflicts for weeks now. If it is for running Coverity Scan with the latest code (which would be really good since the last run was a year ago), then there are better options (see my comments above).

**Comment by rouault** [comment]
@stweil @detonin This is exactly what I've done. I've copied .travis.yml from the existing coverity_scan branch. Then I forked current master as coverity_scan, copied the backuped .travis.yml on it, committed, and force pushed this branch. The run is there: https://travis-ci.org/uclouvain/openjpeg/builds/278117029. So closing this PR

@detonin I've sent a request to access coverity_scan results for the uclouvain/openjpeg project (assuming this is the right one). I guess you need to approve it

**Comment by stweil** [comment]
Thanks.

**Comment by stweil** [comment]
There are now new scan results at https://scan.coverity.com/projects/uclouvain-openjpeg.

**Pull request merged**
