### PR TITLE
Fix #612

### LINKED ISSUE #612: Test 481 reports error in valgrind memcheck
Running the test manually with a debug version of opj_compress built from latest git code:

```
/usr/bin/valgrind "--tool=memcheck" --leak-check=full --show-reachable=yes --verbose --track-origins=yes --num-callers=50 bin/opj_compress -i /openjpeg-data/input/nonregression/Bretagne2.ppm -o /tmp/Bretagne2_3.j2k -EPH -M 38
```

Result:

```
==11019== Conditional jump or move depends on uninitialised value(s)
==11019==    at 0x4E5EAB5: opj_mqc_byteout (mqc.c:219)
==11019==    by 0x4E5EBAB: opj_mqc_renorme (mqc.c:241)
==11019==    by 0x4E5ED47: opj_mqc_codelps (mqc.c:269)
==11019==    by 0x4E5F196: opj_mqc_encode (mqc.c:408)
==11019==    by 0x4E67BA4: opj_t1_enc_clnpass_step (t1.c:853)
==11019==    by 0x4E6838A: opj_t1_enc_clnpass (t1.c:991)
==11019==    by 0x4E69FB9: opj_t1_encode_cblk (t1.c:1617)
==11019==    by 0x4E69CDF: opj_t1_encode_cblks (t1.c:1536)
==11019==    by 0x4E71B96: opj_tcd_t1_encode (tcd.c:2038)
==11019==    by 0x4E704CA: opj_tcd_encode_tile (tcd.c:1226)
==11019==    by 0x4E47608: opj_j2k_write_sod (j2k.c:4296)
==11019==    by 0x4E569E9: opj_j2k_write_first_tile_part (j2k.c:10472)
==11019==    by 0x4E562A4: opj_j2k_post_write_tile (j2k.c:10258)
==11019==    by 0x4E55A21: opj_j2k_encode (j2k.c:10009)
==11019==    by 0x4E604E3: opj_encode (openjpeg.c:737)
==11019==    by 0x407183: main (opj_compress.c:1864)
==11019==  Uninitialised value was created by a heap allocation
==11019==    at 0x4C28C20: malloc (vg_replace_malloc.c:296)
==11019==    by 0x4E6FFAD: opj_tcd_code_block_enc_allocate_data (tcd.c:1083)
==11019==    by 0x4E6FCC5: opj_tcd_init_tile (tcd.c:1008)
==11019==    by 0x4E6FE71: opj_tcd_init_encode_tile (tcd.c:1041)
==11019==    by 0x4E55DCD: opj_j2k_pre_write_tile (j2k.c:10110)
==11019==    by 0x4E55822: opj_j2k_encode (j2k.c:9956)
==11019==    by 0x4E604E3: opj_encode (openjpeg.c:737)
==11019==    by 0x407183: main (opj_compress.c:1864)
[...]
```

All other reported contexts seem to be caused by the same uninitialized tile data.

### PR DESCRIPTION
**Pull request by julienmalik**
Works for me under MemorySanitizer

### CODE REVIEW

**Comment by julienmalik** [comment]
Following @boxerab remark in #612 , I'm testing this fix.
It *does* avoid the uninitialized read.

I don't have much idea about the actual consequences, and about why this test was here in the first place.

So this needs to be validated by the experts :)
ping @detonin @mayeut

**Comment by julienmalik** [comment]
The test for bpno > 0 dates back to the early days, and appeared in 

```
commit 2ad6a9770a867ddc3ecc31f61a248152b7c6eeac
Author: Sebastien Lugan <slugan@users.noreply.github.com>
Date:   Thu Nov 27 10:10:17 2003 +0000

    Initial revision
```

The available history does not go further in the past.

**Comment by boxerab** [comment]
Looks like a 10 year old bug :) Surprising.

**Comment by mayeut** [comment]
My knowledge doesn't go that far... @detonin, any idea ?

**Comment by detonin** [comment]
I've started investigated this bypass and restart problem and created a branch for this: https://github.com/uclouvain/openjpeg/tree/fix-bypass-restart
The whole function t1_encode_cblk would actually need a major refactoring.
For now, the RESTART mode seems to be fixed and the BYPASS mode is behaving better but not lossless yet.
The branch still needs refactoring before merging into master. I'll continue working on it.
ping #612 #674

**Comment by detonin** [comment]
More specifically, part of the problem comes from these lines:
https://github.com/uclouvain/openjpeg/blob/fix-bypass-restart/src/lib/openjp2/t1.c#L1689-L1697
that have been introduced in March 2007 (surprising indeed):
https://github.com/uclouvain/openjpeg/commit/5a3c1ffe7d5b4269d073fa826cba94591c0c3ed5

The FF-bytes management is something quite tricky in JPEG 2000 and the additional arithmetic coder termination brought by the BYPASS and RESTART modes can interfere with the way FF-bytes are usually managed (i.e. removed if they are the last bytes of a coding pass).

**Comment by rouault** [comment]
Fixed per https://github.com/uclouvain/openjpeg/pull/949

**Pull request closed without merging**
