### PR TITLE
[libtiff] Add missing include statement for ssize_t

### PR DESCRIPTION
**Pull request by mayeut**

### CODE REVIEW

**Comment by stweil** [comment]
See also #681.

**Comment by mayeut** [comment]
@stweil yes, but I'd rather include a file that is known to exist rather than presume that it exists because not on Windows.
Either way, will be fixed.

**Comment by stweil** [comment]
Then I'll have to fix #648, too. unistd.h is a standard header file required by POSIX (see https://en.wikipedia.org/wiki/Unistd.h). I know only one vendor which fails to support it.

**Comment by stweil** [comment]
#648 included #681. I fixed that, so now #648 is now a single commit.

**Pull request merged**
