### PR TITLE
ignore wrong icc

### PR DESCRIPTION
**Pull request by szukw000**

### CODE REVIEW

**Comment by szukw000** [comment]
if image->numcomps < 3 but icc outspace > 2 then ignore the icc

**Comment by szukw000** [comment]
@rouault ,
I do not know what the download
```
KDU77_Demo_Apps_for_Win32_150710.msi_.zip
```
is good for on a LINUX machine.
winfried

**Comment by szukw000** [comment]
@rouault ,
```
file KDU77_Demo_Apps_for_Win32_150710.msi

KDU77_Demo_Apps_for_Win32_150710.msi: Composite Document File V2 Document, Little Endian, Os: Windows, Version 6.1, MSI Installer, Create Time/Date: Mon Jun 21 08:00:00 1999, Name of Creating Application: Windows Installer, Security: 1, Code page: 1252, Template: Intel;1033, Number of Pages: 200, Revision Number: {F2000C61-725F-44F4-8460-6E6322093AE4}, Title: Kakadu-demo-apps, Author: The University of New South Wales, Number of Words: 2, Last Saved Time/Date: Fri Jul 10 13:50:17 2015, Last Printed: Fri Jul 10 13:50:17 2015
```
winfried

**Comment by rouault** [comment]
The failure was likely a network flake. I've closed & re-opened the PR to start a new build

**Pull request merged**
