### PR TITLE
Add AVX2 and AVX512 optimization

### PR DESCRIPTION
**Pull request by tszumski**
Encoder: performance gain ~0.1%​
Decoder: performance gain ~2.5%

### CODE REVIEW

**Comment by rouault** [comment]
> Encoder: performance gain ~0.1%​
> Decoder: performance gain ~2.5%

How was that measured? Total performance gain, or just on the DWT?

**Comment by tszumski** [comment]
> > Encoder: performance gain ~0.1%​
> > Decoder: performance gain ~2.5%
> 
> How was that measured? Total performance gain, or just on the DWT?

Total performance gain

**Comment by rouault** [comment]
This breaks at least Windows x64 regression tests.
Did you run the regression test suite locally?  Make sure to clone https://github.com/uclouvain/openjpeg-data in a "data" subdirectory of your openjpeg repository, and run ctest

**Comment by tszumski** [comment]
> This breaks at least Windows x64 regression tests. Did you run the regression test suite locally? Make sure to clone https://github.com/uclouvain/openjpeg-data in a "data" subdirectory of your openjpeg repository, and run ctest

Thanks for reply, I was able to fix it. Root cause is that CI use MSVC 2015 toolset that does not have _mm256_extract_epi32 and _mm256_insert_epi32 intrinsic defined,

**Comment by rouault** [comment]
@tszumski Can you fix the formatting of the code according to the instructions at end of https://github.com/uclouvain/openjpeg/actions/runs/10718601930/job/29724100308?pr=1552, that is
```
* Enable WITH_ASTYLE in your cmake configuration to format C++ code
* Use "scripts/astyle.sh file" to fix the now badly indented files
* Consider using scripts/prepare-commit.sh as pre-commit hook to avoid this
  in the future (ln -s scripts/prepare-commit.sh .git/hooks/pre-commit) or
  run it manually before each commit.
```

**Comment by tszumski** [comment]
> @tszumski Can you fix the formatting of the code according to the instructions at end of https://github.com/uclouvain/openjpeg/actions/runs/10718601930/job/29724100308?pr=1552, that is
> 
> ```
> * Enable WITH_ASTYLE in your cmake configuration to format C++ code
> * Use "scripts/astyle.sh file" to fix the now badly indented files
> * Consider using scripts/prepare-commit.sh as pre-commit hook to avoid this
>   in the future (ln -s scripts/prepare-commit.sh .git/hooks/pre-commit) or
>   run it manually before each commit.
> ```

Fixed

**Comment by rouault** [comment]
@tszumski I don't have hardware to test AVX512F and github CI doesn't seem to have machines with it. Could you paste somewhere (here or a github gist if too large):
- the output of "grep C_FLAGS CMakeCache.txt" , showing that it includes ``-mavx512f``
- the output of "ctest -V"

**Comment by rouault** [comment]
> Failed Tests 1147/1148 are also failing on master branch without my changes

yes, those are "expected" (we have some a file in CI to ignore them

ok, so everything looks good. Merging

**Pull request merged**
