### PR TITLE
CI: Add CIFuzz action

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Add CIFuzz Github action to build and run fuzzers on pull requests.

This will run the fuzzers for 600 seconds (split between all the fuzzers) in the CI when a pull request is made and is a service by OSS-fuzz. It can help with catching bugs early and catch regressions.

Documentation for CIFuzz can be found here: https://google.github.io/oss-fuzz/getting-started/continuous-integration/

Signed-off-by: David Korczynski <david@adalogics.com>

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
I think the reason the CIFuzz check fails is https://github.com/google/oss-fuzz/issues/6755 
Fix here https://github.com/google/oss-fuzz/pull/6934

**Comment by DavidKorczynski** [comment]
CIFuzz should be fixed now, could we retrigger the CI?

**Comment by DavidKorczynski** [comment]
Current issue with CIFuzz is being tracked here https://github.com/google/oss-fuzz/issues/6952

**Comment by jvoisin** [comment]
@DavidKorczynski can you rebase this PR and re-trigger the CI?

**Pull request merged**
