### PR TITLE
Correct lossless issue on linux x86

### PR DESCRIPTION
**Pull request by mayeut**
Update uclouvain/openjpeg#571

### CODE REVIEW

**Comment by malaterre** [comment]
this fixes the symptoms, not the bug

**Comment by mayeut** [comment]
@malaterre,

opj_tcd_makelayer takes a threshold that's computed in opj_tcd_rateallocate

the computation for the threshold in case of lossless transform is identical to the computation in  opj_tcd_makelayer. Thus, it expects "computation" == stored_threshold to be true at some point.
The stored threshold will always be rounded to 64bits. "computation" precision will depend on compilation options, architectures, ...

IMHO, this PR removes the dependency on 64bits precision.

If you fill it does not fix the issue properly, I'll revert the "invalid fix" & only merge the tests in.

**Comment by mayeut** [comment]
@malaterre,

Given the definition of DBL_EPSILON:
```c
#define DBL_EPSILON     2.2204460492503131e-016 /* smallest such that 1.0+DBL_EPSILON != 1.0 */
```
It might not be a good fix.

We might want to make the check with epsilon directly in the test in opj_tcd_makelayer
```c
if ((thresh - (dd / dr)) <= DBL_EPSILON) /* do not rely on float equality, check with DBL_EPSILON margin */
	n = passno + 1;
```

I think the later would be OK, do you  agree ?

**Comment by malaterre** [comment]
@mayeut that's a lot better ! I still do not like the equality (does not work for floating point anyway). So I would write:
```
if ((thresh - (dd / dr)) < DBL_EPSILON)
```

Do we need an `fabs` here also ?

**Comment by mayeut** [comment]
@malaterre,

I removed ```=``` from the test. It's now:
```c
if ((thresh - (dd / dr)) < DBL_EPSILON)
```

``` fabs``` would have been needed if original test was ```==```. This is not the case here.

**Comment by malaterre** [comment]
ACK. Everything is fine for me. Thx

**Pull request merged**
