### PR TITLE
Build: fix linking of executables on some systems where TIFF/LCMS2 static libraries are not in system directories (fixes #1430)

### LINKED ISSUE #1430: OSX m1 v2.5.0 build fail
## Expected behavior and actual behavior.

Expected: build completed.
Actual: build failed.

Error:

```
Linking C executable ../../../bin/opj_decompress
ld: library not found for -ltiff
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/opj_decompress] Error 1
make[1]: *** [src/bin/jp2/CMakeFiles/opj_decompress.dir/all] Error 2
make: *** [all] Error 2
```

## Steps to reproduce the problem.

```bash
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
make
```

## Operating system

OSX 12.4 m1

## openjpeg version

v2.5.0

## Additional info

v2.4.0 - build works ok.

```bash
brew info libtiff
libtiff: stable 4.4.0 (bottled)
TIFF library and utilities
https://libtiff.gitlab.io/libtiff/
/opt/homebrew/Cellar/libtiff/4.4.0 (249 files, 4.8MB) *
```

### PR DESCRIPTION
**Pull request by rouault**
Note that the fix might be partial only for static-only builds (cf
comments)

Ammends PR #866 and #867

CC @ffontaine / @pseiderer

### CODE REVIEW

**Comment by ffontaine** [comment]
I'm a little bit lost, `TIFF_LIBNAME` is set to  `${TIFF_LIBRARIES} ${PC_TIFF_STATIC_LIBRARIES}` which seems right except if `${PC_TIFF_STATIC_LIBRARIES}` is "broken"  on osx and contains a non existing path resulting in a build failure. Did I missed something?

**Comment by rouault** [comment]
> except if `${PC_TIFF_STATIC_LIBRARIES}` is "broken" on osx and contains a non existing path resulting in a build failure.

PC_TIFF_STATIC_LIBRARIES on my Ubuntu 20.04 is "tiff;webp;zstd;lzma;jbig;jpeg;z;m" . Which is OK, but this variable doesn't contain paths, which causes the issue on distributions where the libraries are not in a system library directory. Presumably this should be combined with PC_TIFF_STATIC_LIBS_PATHS to build fully expanded library names.

**Comment by rouault** [comment]
> I fear that it will break the build of `openjp2_static` when `BUILD_SHARED_LIBS` and `BUILD_STATIC_LIBS` are both set to `ON`

yes that's likely. Perhaps do 2 separate builds. Static builds with dependency tracking are quite difficult to get right, and openjpeg that attempts to do both at the same time make it even more challenging.

**Comment by ffontaine** [comment]
Indeed, we should definitely remove the `BR2_SHARED_STATIC_LIBS` option in buildroot.
Thanks for pinging me about this change. I'll be able to correctly handle the bump of openjpeg in buildroot.

**Pull request merged**
