### PR TITLE
Fix potential out-of-bounds read (coverity) 

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
The last update for Coverity Scan was more than two years ago. An update would be really helpful.

**Comment by mayeut** [comment]
@malaterre , you might wan't this in branch 2.1 for openjpip package

**Comment by stweil** [comment]
> The last update for Coverity Scan was more than two years ago. An update would be really helpful.

I just noticed that there are two entries for OpenJPEG on Coverity Scan:

* [openjpeg](https://scan.coverity.com/projects/openjpeg) (last update 2014?)
* [uclouvain-openjpeg](https://scan.coverity.com/projects/uclouvain-openjpeg) (last update 2016-09)

This is a little bit confusing.

**Comment by mayeut** [comment]
@stweil, the one used by travis-ci is  [uclouvain-openjpeg](https://scan.coverity.com/projects/uclouvain-openjpeg) . I think there was some problem with the old one at some point. Maybe @detonin  has more info about this.

**Comment by detonin** [comment]
@stweil yes there was a bug on coverity website preventing to link the legacy account with the github repo so we add to create a new one. I should probably close the old one and invite people on uclouvain-openjpeg.

**Pull request merged**
