### PR TITLE
Refactor opj_j2k_read_ppm & opj_j2k_read_ppt

### PR DESCRIPTION
**Pull request by mayeut**
Update uclouvain/openjpeg#470
Update uclouvain/openjpeg#288
Update uclouvain/openjpeg#532

### CODE REVIEW

**Comment by mayeut** [comment]
Test data already updated in openjpeg-data
All tests are OK under CDash.

**Comment by mayeut** [comment]
@detonin, could you have a look at this one and tell me if it's consistent with what's asked in #470

**Comment by detonin** [comment]
Seems consistent indeed with #470 indeed. Great job.

Before merging, there is some kind of regression issue. I ran test suite and get 5 additional tests succeeding but 9 more failing:
http://my.cdash.org/viewTest.php?onlydelta&buildid=796159
What do you have on your side ?

**Comment by mayeut** [comment]
@detonin,

Can you check the version of master branch used to test the pull request ?
I suspect the PNG & TIFF updates are not applied (those tests where updated, see for TIFF in PR #535, for PNG I removed the screen gamma to get consistent conversions - see comment in code).

**Comment by detonin** [comment]
@mayeut My mistake indeed I forgot to merge master in pr/533 before running the test suite.
http://my.cdash.org/viewTest.php?buildid=796217
Test are ok now (18 failing only) but total time went from 3m29 to 5m11. I did not yet investigate what takes longer but this would be interesting to know.

**Comment by mayeut** [comment]
@detonin,
There are much more tests so that seems fair to get an increase.

**Pull request merged**
