### PR TITLE
issue #695 MQ Encode: ensure that bp pointer never points to uninitialized memory

### LINKED ISSUE #695: MQ Coder encode: Conditional jump or move depends on uninitialised value(s)
http://my.cdash.org/viewDynamicAnalysisFile.php?id=3409924

      if (*mqc->bp == 0xff) {
		mqc->bp++;
		*mqc->bp = (OPJ_BYTE)(mqc->c >> 20);
		mqc->c &= 0xfffff;
		mqc->ct = 7;
	} else {

This is because mq->bp is initialized to one less than the actual data start address.
It could be possible for uninitialized memory to be equal to 0xFF, in which case there will be an error in the code stream. For lossless encoding, this could lead to lossy encoding.

An easy fix is to check if `mqc->bp < mqc->start` before entering the if statement.
On a modern CPU with branch prediction, there should be no performance hit.

### PR DESCRIPTION
**Pull request by boxerab**
fixes #695

### CODE REVIEW

**Comment by boxerab** [comment]
This has to fix the uninitialized memory issue. What I find surprising is that such a critical bug has existed for so long ( > 5 years )

**Comment by mayeut** [comment]
@boxerab, Unfortunately, this doesn't help: http://my.cdash.org/viewDynamicAnalysisFile.php?id=3438342

**Comment by boxerab** [comment]
The patch fixes a definite bug: there may be other similar bugs in the MQ coder that continue causing a valgrind error.

**Comment by detonin** [comment]
@boxerab @mayeut does this fix #612 ?

**Comment by julienmalik** [comment]
I'm currently looking into refreshing the dashboard submissions from CS, which are currently only noise since the GitHub migration, because they are still looking for updates from svn :)

Seeing all the work achieve with Travis, I will remove most of them, but try to setup again the valgrind build where we should see the effect of this patch.

**Comment by boxerab** [comment]
Unfortunately, I don't have time to look into this at the moment.

**Comment by julienmalik** [comment]
@detonin : no it does not fix #612 : http://my.cdash.org/viewDynamicAnalysisFile.php?id=3567436

**Pull request merged**
