### PR TITLE
Update PNG support

### PR DESCRIPTION
**Pull request by mayeut**
Only input modified for now
Update uclouvain/openjpeg#536
Update uclouvain/openjpeg#264

### CODE REVIEW

**Comment by szukw000** [comment]
@mayeut , which version of libpng do you use? I use libpng-1.7.0beta63 and get the
following results.

winfried

openjpeg-2.x-trunk-r3007:

The following tests FAILED:
    578 - NR-ENC-issue316.png-25-decode-ref (Failed)
    579 - NR-ENC-issue316.png-25-compare_dec-ref-out2base (Failed)
    580 - NR-ENC-basn6a08.png-26-encode (Failed)
    581 - NR-ENC-basn6a08.png-26-dump (Failed)
    582 - NR-ENC-basn6a08.png-26-compare_dump2base (Failed)
    583 - NR-ENC-basn6a08.png-26-decode-ref (Failed)
    584 - NR-ENC-basn6a08.png-26-compare_dec-ref-out2base (Failed)

openjpeg-2015-07-20:

The following tests FAILED:
    578 - NR-ENC-issue316.png-25-decode-ref (Failed)
    579 - NR-ENC-issue316.png-25-compare_dec-ref-out2base (Failed)
    583 - NR-ENC-basn6a08.png-26-decode-ref (Failed)
    584 - NR-ENC-basn6a08.png-26-compare_dec-ref-out2base (Failed)
    588 - NR-ENC-issue203-8bpp-width1.bmp-27-decode-ref (Failed)
    833 - NR-ENC-basn0g01.png-76-decode-ref (Failed)
    834 - NR-ENC-basn0g01.png-76-compare_dec-ref-out2base (Failed)
    838 - NR-ENC-basn0g02.png-77-decode-ref (Failed)
    839 - NR-ENC-basn0g02.png-77-compare_dec-ref-out2base (Failed)
    843 - NR-ENC-basn0g04.png-78-decode-ref (Failed)
    844 - NR-ENC-basn0g04.png-78-compare_dec-ref-out2base (Failed)
    848 - NR-ENC-basn0g08.png-79-decode-ref (Failed)
    849 - NR-ENC-basn0g08.png-79-compare_dec-ref-out2base (Failed)
    853 - NR-ENC-basn0g16.png-80-decode-ref (Failed)
    854 - NR-ENC-basn0g16.png-80-compare_dec-ref-out2base (Failed)
    858 - NR-ENC-basn2c08.png-81-decode-ref (Failed)
    859 - NR-ENC-basn2c08.png-81-compare_dec-ref-out2base (Failed)
    863 - NR-ENC-basn2c16.png-82-decode-ref (Failed)
    864 - NR-ENC-basn2c16.png-82-compare_dec-ref-out2base (Failed)
    868 - NR-ENC-basn3p01.png-83-decode-ref (Failed)
    869 - NR-ENC-basn3p01.png-83-compare_dec-ref-out2base (Failed)
    873 - NR-ENC-basn3p02.png-84-decode-ref (Failed)
    874 - NR-ENC-basn3p02.png-84-compare_dec-ref-out2base (Failed)
    878 - NR-ENC-basn3p04.png-85-decode-ref (Failed)
    879 - NR-ENC-basn3p04.png-85-compare_dec-ref-out2base (Failed)
    883 - NR-ENC-basn3p08.png-86-decode-ref (Failed)
    884 - NR-ENC-basn3p08.png-86-compare_dec-ref-out2base (Failed)
    888 - NR-ENC-basn4a08.png-87-decode-ref (Failed)
    889 - NR-ENC-basn4a08.png-87-compare_dec-ref-out2base (Failed)
    893 - NR-ENC-basn4a16.png-88-decode-ref (Failed)
    894 - NR-ENC-basn4a16.png-88-compare_dec-ref-out2base (Failed)
    898 - NR-ENC-basn6a16.png-89-decode-ref (Failed)
    899 - NR-ENC-basn6a16.png-89-compare_dec-ref-out2base (Failed)
    903 - NR-ENC-ftbbn0g01.png-90-decode-ref (Failed)
    904 - NR-ENC-ftbbn0g01.png-90-compare_dec-ref-out2base (Failed)
    908 - NR-ENC-ftbbn0g02.png-91-decode-ref (Failed)
    909 - NR-ENC-ftbbn0g02.png-91-compare_dec-ref-out2base (Failed)
    913 - NR-ENC-ftbbn0g04.png-92-decode-ref (Failed)
    914 - NR-ENC-ftbbn0g04.png-92-compare_dec-ref-out2base (Failed)
    917 - NR-ENC-ftbbn2c16.png-93-compare_dump2base (Failed)
    918 - NR-ENC-ftbbn2c16.png-93-decode-ref (Failed)
    919 - NR-ENC-ftbbn2c16.png-93-compare_dec-ref-out2base (Failed)
    923 - NR-ENC-ftbbn3p08.png-94-decode-ref (Failed)
    924 - NR-ENC-ftbbn3p08.png-94-compare_dec-ref-out2base (Failed)
    927 - NR-ENC-ftbgn2c16.png-95-compare_dump2base (Failed)
    928 - NR-ENC-ftbgn2c16.png-95-decode-ref (Failed)
    929 - NR-ENC-ftbgn2c16.png-95-compare_dec-ref-out2base (Failed)
    933 - NR-ENC-ftbgn3p08.png-96-decode-ref (Failed)
    934 - NR-ENC-ftbgn3p08.png-96-compare_dec-ref-out2base (Failed)
    938 - NR-ENC-ftbrn2c08.png-97-decode-ref (Failed)
    939 - NR-ENC-ftbrn2c08.png-97-compare_dec-ref-out2base (Failed)
    942 - NR-ENC-ftbwn0g16.png-98-compare_dump2base (Failed)
    943 - NR-ENC-ftbwn0g16.png-98-decode-ref (Failed)
    944 - NR-ENC-ftbwn0g16.png-98-compare_dec-ref-out2base (Failed)
    948 - NR-ENC-ftbwn3p08.png-99-decode-ref (Failed)
    949 - NR-ENC-ftbwn3p08.png-99-compare_dec-ref-out2base (Failed)
    953 - NR-ENC-ftbyn3p08.png-100-decode-ref (Failed)
    954 - NR-ENC-ftbyn3p08.png-100-compare_dec-ref-out2base (Failed)
    958 - NR-ENC-ftp0n0g08.png-101-decode-ref (Failed)
    959 - NR-ENC-ftp0n0g08.png-101-compare_dec-ref-out2base (Failed)
    963 - NR-ENC-ftp0n2c08.png-102-decode-ref (Failed)
    964 - NR-ENC-ftp0n2c08.png-102-compare_dec-ref-out2base (Failed)
    968 - NR-ENC-ftp0n3p08.png-103-decode-ref (Failed)
    969 - NR-ENC-ftp0n3p08.png-103-compare_dec-ref-out2base (Failed)
    973 - NR-ENC-ftp1n3p08.png-104-decode-ref (Failed)
    974 - NR-ENC-ftp1n3p08.png-104-compare_dec-ref-out2base (Failed)

**Comment by mayeut** [comment]
@szukw000 , I use libpng from third party.

Could you run tests under CDash in order to check those errors easily please ?

**Comment by szukw000** [comment]
@mayeut , both done.

Site name: mary
Build name: Linux-(mary-4.1.0-#2-SMP-x86_64-AMD-FX(tm)-6100-Six-Core-Processor)

The TCL file does not show spaces.

winfried

**Comment by detonin** [comment]
@mayeut Many thanks for integrating png suite.
@szukw000 I think you did not update your openjpeg-data repo to fetch new png files.

**Comment by mayeut** [comment]
@szukw000,

openjpeg-data seems up to date. However, kakadu doesn't work properly as can be seen with all decode-ref tests failing.
Here's the output from one:
```
/usr/local/bin/kdu_expand: error while loading shared libraries: libkdu_v74R.so: cannot open shared object file: No such file or directory
```

**Pull request merged**
