### PR TITLE
Removed deprecated code.

### PR DESCRIPTION
**Pull request by dlemstra**
I can see there are plans to bump to `OPENJPEG_SOVERSION` in 2.2.0 (https://github.com/uclouvain/openjpeg/blob/master/CMakeLists.txt#L57). I think it is now time to remove the last bits of deprecated code. This patch removes the deprecated fields from opj_cparameters:

- cp_cinema and cp_rsiz have been deprecated since April 2014 (7199d9b).
- index_on and index have been deprecated since November 2007 (c458af9).

This patch also bumps `OPENJPEG_SOVERSION` from 7 to 8.

### CODE REVIEW

**Comment by dlemstra** [comment]
@rouault Are you interested in this pull request and should I fix the conflicts or should I close this issue?

**Comment by rouault** [comment]
@detonin What is your opinion on this ?This will change the ABI

**Comment by detonin** [comment]
@dlemstra Thanks for the follow-up. Eventually we do not plan to bump the SOVERSION for the next release (upcoming 2.2.1) so that the drastically improved performances are available to users by a drop-in replacement of their version of the openjp2 library. However, we definitely plan to clean the API in a near future so this issue should remain open.

**Comment by dlemstra** [comment]
Okay.  Let me know when you are planning to do a version bump and I will fix the pull request.

**Comment by dlemstra** [comment]
Would you want me to update this PR @detonin and @rouault or should I close it?

**Comment by rouault** [comment]
I'm a bit indifferent regarding this. I noticed recently that there are other "ghost" things in openjpeg.h that could deserve cleaning, like opj_tp_info_t, opj_tile_info_t, opj_codestream_info_t. The final word belongs to @detonin as the release manager

**Pull request closed without merging**
