### PR TITLE
opj_free cannot be found

### PR DESCRIPTION
**Pull request by szukw000**
opj_free() cannot be found in JP3D.Use free() instead.

### CODE REVIEW

**Comment by rouault** [comment]
Are you (or anyone) actually using JP3D ?

**Comment by szukw000** [comment]
@rouault ,
no, I do not use it now. I only compile it. 
A JP3D-testfile would be nice to see where the traps are.
winfried

**Comment by rouault** [comment]
We should probably get rid of anything that is not libopenjp2

**Comment by ValZapod** [comment]
https://github.com/uclouvain/openjpeg/blob/157df528ac4dccd26d8e4fd39b6eac218cafddba/src/bin/jp3d/opj_jp3d_compress.c#L978

So LGTM, that part of codebase uses only free() (just like jp2 stuff)

https://github.com/uclouvain/openjpeg/blob/157df528ac4dccd26d8e4fd39b6eac218cafddba/src/bin/jp2/convert.c#L2300

Interesting choice for functions that use only opj_free BTW

http://www.openjpeg.org/doxygen/group___m_i_s_c.html#ga2bd00e2482ae36197631bde0665cfdfe

**Comment by rouault** [comment]
@ValZapod are you making real-life use of that part of the code base ?

**Comment by ValZapod** [comment]
> @ValZapod are you making real-life use of that part of the code base ?

I am confusion. Are you trying to say that 3D in by itself is not used anymore? That is not true. VR is 3D. Any normal game and many science tools are by definition 3D. You can hack modern TVs to use 3D Vision even though there is no official support in them. That is LG C9... So...

**Comment by ValZapod** [comment]
Also there are some 3d stuff here (not JP3D AFAIK) https://github.com/Ymagis/ClairMeta_Data/tree/master/DCP

**Comment by rouault** [comment]
> Are you trying to say that 3D in by itself is not used anymore?

I'm not talking about 3D in general, but about this JP3D component ! I've the feeling that it is abandoned code and I seriously consider proposing we remove that off from the codebase so people aren't distracted by code that isn't used.

**Comment by ValZapod** [comment]
Well, first of all JP3D is JPEG2000 Part 10, is it not? See #1282. I mean... 

Now, very fast search in arxiv gives [this article](https://arxiv.org/pdf/1705.06611.pdf) that talks about "JP3D from OpenJPEG". Some samples are here, http://people.fisica.uniroma2.it/~solare/en/?p=257 So... I can search though other databases?

**Comment by ValZapod** [comment]
opj_free is only in src/lib, interesting how did this happen?? Ah, okay! In the past it was libopenjp3d https://github.com/uclouvain/openjpeg/blob/5303ac6dc8d718f6295427dd349cf61827253b1b/libopenjp3d/volume.c#L86

**Comment by ValZapod** [comment]
So, I vote to merge that...

**Comment by ValZapod** [comment]
This will fix #1327, the patch already cherry-picked in Debian. https://salsa.debian.org/debian-phototools-team/openjpeg2/-/blob/master/debian/patches/opj_free.patch

So please merge, @rouault.

**Comment by malaterre** [comment]
@rouault I understand your comment, however there are really two issues here:

1. Nobody (but me) actually ever used JP3D,
2. opj 2.4.0 was released with a piece of (mostly) unused code that does not compile (this is an issue for distro maintainer).

I'd suggest you merge #1323 for now, and open a proposal / PR that will remove JP3D for the next major release. thanks for maintaining opj.

cc: @detonin

**Comment by malaterre** [comment]
ping @ichlubna

**Comment by ichlubna** [comment]
We have used JP3D in our [research](https://www.fit.vut.cz/research/publication/11970/.en)

**Comment by ValZapod** [comment]
BTW, while there also apply https://github.com/uclouvain/openjpeg/issues/878#issuecomment-722037293 @szukw000, please ;)

**Comment by rouault** [comment]
PR no longer relevant since https://github.com/uclouvain/openjpeg/pull/1350

**Pull request closed without merging**
