### PR TITLE
Tests for AFL files

### PR DESCRIPTION
**Pull request by szukw000**
Tests for files changed by AFL

### CODE REVIEW

**Comment by szukw000** [comment]
@rouault ,
Some library bugs are really obvious. E.g. in 'imagetotif' the developer
used his owns types instead of the libtiff types:

ISSUE-871/1-000007.tif:

bin/opj_compress -i ../../ISSUE-871/1-000007.tif -o 871-1-000007.tif.jp2

TIFFFetchNormalTag: Warning, IO error during reading of "XResolution"; tag ignored.
TIFFFetchNormalTag: Warning, IO error during reading of "YResolution"; tag ignored.
_TIFFVSetField: ../../ISSUE-871/1-000007.tif: Null count for "ICC Profile" (type 7, writecount -3, passcount 1).
TIFFFillStrip: Invalid strip byte count 0, strip 1.
Segmentation fault

vs.

opj_compress -i ISSUE-871/1-000007.tif  -o 871-1-000007.tif.jp2

TIFFFetchNormalTag: Warning, IO error during reading of "XResolution"; tag ignored.
TIFFFetchNormalTag: Warning, IO error during reading of "YResolution"; tag ignored.
_TIFFVSetField: ISSUE-871/1-000007.tif: Null count for "ICC Profile" (type 7, writecount -3, passcount 1).
TIFFFillStrip: Invalid strip byte count 0, strip 1.
tiftoimage: Bad value for ssize(-1) vs. strip_size(1024).
        Aborting.
Unable to load tiff file


In convert.c, line 1946: 'are_comps_similar(image)' may return OPJ_FALSE.
OPJ_FALSE is ignored.
I suppose the test in line 1900:

                (i <= 2 &&
                 (image->comps[0].prec != image->comps[i].prec ||
                  image->comps[0].sgnd != image->comps[i].sgnd))

is wrong and should be 'i >= 2' for RGB and RGBA.

In j2k.c, line 1927 : p_j2k->cstr_index->main_head_start may be '0'.
Other values are > 0. Is '0' a bug?

./decompress.sh issue880-poc2.j2k

[INFO] Start to read j2k main header (0).
[WARNING] Unknown marker
[WARNING] Cannot take in charge collections without same number of indixes
[WARNING] Unknown marker
[WARNING] Cannot take in charge multiple MCT markers
[WARNING] Cannot take in charge collections other than array decorrelation
[WARNING] Unknown marker
[WARNING] Cannot take in charge multiple MCT markers
[WARNING] Unknown marker
[WARNING] Cannot take in charge multiple MCT markers
[WARNING] Unknown marker
[WARNING] Cannot take in charge multiple MCT markers
[WARNING] Cannot take in charge multiple MCT markers
[WARNING] Unknown marker
[WARNING] Cannot take in charge multiple MCT markers
[WARNING] Unknown marker
[WARNING] Cannot take in charge multiple MCT markers
[WARNING] Unknown marker
[WARNING] Cannot take in charge multiple MCT markers
[WARNING] Cannot take in charge multiple MCT markers
[WARNING] Unknown marker
[WARNING] Cannot take in charge multiple MCT markers
[WARNING] Unknown marker
[WARNING] Cannot take in charge collections without same number of indixes
[WARNING] Unknown marker
[WARNING] Unknown marker
[WARNING] Cannot take in charge multiple transformation stages.
[WARNING] Unknown marker
[INFO] Stream reached its end !
[ERROR] Stream too short
ERROR -> opj_decompress: failed to read the header

In convertbmp.c, line 835:

 fprintf(stderr, "Unsupported number of components: %d\n", image->comps[0].prec);

must run:

 fprintf(stderr, "imagetobmp: Unsupported precision: %d\n", image->comps[0].prec);

Most files crash because of different values for IHDR(w,h) vs. SIZ(w,h).


winfried

**Comment by rouault** [comment]
Why did you close the PR ?
The AFL test comments don't bring anything. They should be removed or replaced by something more meaningful
There are likely formatting issues. Build with "cmake -DWITH_ASTYLE=ON" and then run scripts/prepare-commit.sh to reformat

**Comment by rouault** [comment]
> In convert.c, line 1946: 'are_comps_similar(image)' may return OPJ_FALSE.
> OPJ_FALSE is ignored.
> I suppose the test in line 1900:
> 
>             (i <= 2 &&
>              (image->comps[0].prec != image->comps[i].prec ||
>               image->comps[0].sgnd != image->comps[i].sgnd))
> 
> is wrong and should be 'i >= 2' for RGB and RGBA.

I believe this is correct. The intent here was to allow the alpha channel of a RGBA image to be of a different precision (typically 1 bit).

**Comment by szukw000** [comment]
@rouault ,
maybe the code is correct. But nevertheless the case OPJ_FALSE is not handled.
I deleted the PR because I did not find the 'Create pull request' button.

winfried

**Comment by rouault** [comment]
> But nevertheless the case OPJ_FALSE is not handled.

In the OPJ_FALSE case, you end up in the "YUV or MONO:" case at line 2098, so this is "handled"

> I deleted the PR because I did not find the 'Create pull request' button.

I'm confused. This page is a pull request, so you did find the 'create pull request' button at some point...

**Comment by szukw000** [comment]
@rouault ,
the following archive is the minimal set of images for the tests.
winfried
[openjpeg-crashes-2017-07-30.zip](https://github.com/uclouvain/openjpeg/files/1187132/openjpeg-crashes-2017-07-30.zip)

**Comment by rouault** [comment]
Can you reopen the pull request so that tests run ?

**Comment by rouault** [comment]
Ah ok so #975 is the new PR apparently

**Pull request closed without merging**
