### PR TITLE
fix: use `opj_uint_ceildiv` instead of `opj_int_ceildiv` when necessary

### LINKED ISSUE #1438: Integer Overflow in `src/lib/openjp2/image.c`
##### System information (version)

- Operating System => Ubuntu 20.04
- Compiler => clang-14

##### Detailed description

Hi! We've been fuzzing [OpenCV](https://github.com/opencv/opencv) project and found integer overflow error in openjpeg in `opencv/3rdparty/openjpeg/openjp2/image.c:134` (or `openjpeg/src/lib/openjp2/image.c:134` in your project):

    l_y1 = p_cp->ty0 + (p_cp->th - 1U) * p_cp->tdy; /* can't overflow */

Overflow occurs both in addition and multiplication operations. Comment says overflow cannot occur, but actually it can.

##### Steps to reproduce

1. Build docker container from here: https://github.com/ispras/oss-sydr-fuzz/tree/master/projects/opencv

        sudo docker build -t oss-sydr-fuzz-opencv .

2. Run docker container:

        sudo docker run --rm -v `pwd`:/fuzz -it oss-sydr-fuzz-opencv /bin/bash

3. Run `imdecode_fuzzer` target on pinned input 
[sydr_b9c0c566285af1d73e93f3e8ba9f4c3a06df0215_int_overflow_24_unsigned.txt](https://github.com/opencv/opencv/files/9168316/sydr_b9c0c566285af1d73e93f3e8ba9f4c3a06df0215_int_overflow_24_unsigned.txt)

        /out/imdecode_fuzzer /fuzz/imdecode-out/security-verified/sydr_b9c0c566285af1d73e93f3e8ba9f4c3a06df0215_int_overflow_24_unsigned

4. You will see following sanitizer output:

        /opencv/3rdparty/openjpeg/openjp2/image.c:134:40: runtime error: unsigned integer overflow: 2 * 4278190076 cannot be represented in type 'unsigned int'
        SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /opencv/3rdparty/openjpeg/openjp2/image.c:134:40 in 
        /opencv/3rdparty/openjpeg/openjp2/image.c:134:22: runtime error: unsigned integer overflow: 50331631 + 4261412856 cannot be represented in type 'unsigned int'
        SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /opencv/3rdparty/openjpeg/openjp2/image.c:134:22 in

We created the same issue for OpenCV: opencv/opencv#22284

### PR DESCRIPTION
**Pull request by mayeut**
There are a bunch of loc where we can see a usage of `opj_int_ceildiv`:
```
(OPJ_UINT32)opj_int_ceildiv((OPJ_INT32)a, (OPJ_INT32)b);
```
where a & b are `OPJ_UINT32`.

This can lead to overflow/underflow for some a/b combinations.
Replace those calls by `opj_uint_ceildiv` instead to always get a correct result.

This also allows some valid single tile images with huge tile size to be decoded properly.
Fix #1438

Requires data from https://github.com/uclouvain/openjpeg-data/pull/24

### CODE REVIEW

**Comment by rouault** [comment]
can you git commit --amend & git push -f to force CI to restart now that has been merged https://github.com/uclouvain/openjpeg/pull/1482?

**Comment by mayeut** [comment]
I'm seeing the same tests failures for "regular" on master in my fork: https://github.com/mayeut/openjpeg/actions/runs/6278478237/job/17052321449

Not sure how to go forward.

**Comment by rouault** [comment]
> Not sure how to go forward.

maybe try renaming the existing tools/travis-ci/knownfailures-Ubuntu22.04-gcc11.3.0-x86_64-Release-3rdP.txt file as tools/travis-ci/knownfailures-Ubuntu22.04-gcc11.4.0-x86_64-Release-3rdP.txt since there's appear to have been an upgrade from gcc 11.3 to 11.4

**Comment by Jamaika1** [comment]
```
j2k.c: In function 'opj_j2k_dump_MH_info':
j2k.c:11341:35: error: expected ')' before 'PRIu32'
11341 |     fprintf(out_stream, "\t tx0=%" PRIu32 ", ty0=%" PRIu32 "\n", p_j2k->m_cp.tx0,
      |            ~                      ^~~~~~~
      |                                   )
j2k.c:45:1: note: 'PRIu32' is defined in header '<inttypes.h>'; did you forget to '#include <inttypes.h>'?
   44 | #include "opj_includes.h"
  +++ |+#include <inttypes.h>
   45 |
j2k.c:11343:35: error: expected ')' before 'PRIu32'
11343 |     fprintf(out_stream, "\t tdx=%" PRIu32 ", tdy=%" PRIu32 "\n", p_j2k->m_cp.tdx,
      |            ~                      ^~~~~~~
      |                                   )
j2k.c:11343:36: note: 'PRIu32' is defined in header '<inttypes.h>'; did you forget to '#include <inttypes.h>'?
11343 |     fprintf(out_stream, "\t tdx=%" PRIu32 ", tdy=%" PRIu32 "\n", p_j2k->m_cp.tdx,
      |                                    ^~~~~~
j2k.c:11345:34: error: expected ')' before 'PRIu32'
11345 |     fprintf(out_stream, "\t tw=%" PRIu32 ", th=%" PRIu32 "\n", p_j2k->m_cp.tw,
      |            ~                     ^~~~~~~
      |                                  )
j2k.c:11345:35: note: 'PRIu32' is defined in header '<inttypes.h>'; did you forget to '#include <inttypes.h>'?
11345 |     fprintf(out_stream, "\t tw=%" PRIu32 ", th=%" PRIu32 "\n", p_j2k->m_cp.tw,
      |                                   ^~~~~~
```

**Comment by rouault** [comment]
@Jamaika1 does https://github.com/uclouvain/openjpeg/pull/1483 do the job ?

**Comment by mayeut** [comment]
@rouault,

with  https://github.com/uclouvain/openjpeg/pull/1450 (which goes with "Remove support for non-C99 compilers (like VS2010) that don't support snprintf()"), support for MSVC versions prior to vs2015 is dropped (https://stackoverflow.com/questions/2915672/snprintf-and-visual-studio-2010).

This means that all supported MSVC versions do have `stdint.h` & `inttypes.h` now.
For non windows platforms, those headers were mandatory.

I can either add a definition for `PRIu32` in the current `opj_inttypes.h` or just make those headers mandatory altogether.

I'd rather go with the second option.

Any thoughts ?

**Comment by rouault** [comment]
> I'd rather go with the second option.

ah yes, but @Jamaika1 how come inttypes.h isn't detected on your gcc windows ? Are you using an antiquated version ?

**Comment by mayeut** [comment]
@Jamaika1, were you defining `-DOPJ_HAVE_INTTYPES_H=0` and/or `-DOPJ_HAVE_STDINT_H=0` in your cmake configure step rather than letting cmake find/define those ?

**Comment by Jamaika1** [comment]
I'm amateur who decided to manually assemble ffmpeg in gcc. There are lot of additions and bugs.
I use c/c++11.
I have this record:
As I understand it, in mingw64 I should not use inttypes.h, sys/types.h, sys/types.h, sys/stat.h
```
#if (defined(__STDC__) && __STDC__ && __STDC_VERSION__ >= 199901L) || (defined(__GNUC__) && (defined(_STDINT_H) || defined(_STDINT_H_)) || defined (HAVE_STDINT_H))
#include <stdint.h>

   typedef int16_t celt_int16;
   typedef uint16_t celt_uint16;
   typedef int32_t celt_int32;
   typedef uint32_t celt_uint32;
#elif defined(_WIN32) 

#  if defined(__CYGWIN__)
#    include <_G_config.h>
     typedef _G_int32_t celt_int32;
     typedef _G_uint32_t celt_uint32;
     typedef _G_int16 celt_int16;
     typedef _G_uint16 celt_uint16;
#  elif defined(__MINGW32__)
     typedef short celt_int16;
     typedef unsigned short celt_uint16;
     typedef int celt_int32;
     typedef unsigned int celt_uint32;
#  elif defined(__MWERKS__)
     typedef int celt_int32;
     typedef unsigned int celt_uint32;
     typedef short celt_int16;
     typedef unsigned short celt_uint16;
#  else
     /* MSVC/Borland */
     typedef __int32 celt_int32;
     typedef unsigned __int32 celt_uint32;
     typedef __int16 celt_int16;
     typedef unsigned __int16 celt_uint16;
#  endif

#elif defined(__MACOS__)

#  include <sys/types.h>
   typedef SInt16 celt_int16;
   typedef UInt16 celt_uint16;
   typedef SInt32 celt_int32;
   typedef UInt32 celt_uint32;

#elif (defined(__APPLE__) && defined(__MACH__)) /* MacOS X Framework build */

#  include <sys/types.h>
   typedef int16_t celt_int16;
   typedef u_int16_t celt_uint16;
   typedef int32_t celt_int32;
   typedef u_int32_t celt_uint32;

#elif defined(__BEOS__)

   /* Be */
#  include <inttypes.h>
   typedef int16 celt_int16;
   typedef u_int16 celt_uint16;
   typedef int32_t celt_int32;
   typedef u_int32_t celt_uint32;

#else 
```

**Comment by rouault** [comment]
> in mingw64 (no POSIX) I should not use inttypes.h

inttypes.h is a standard headers that all C99 and C++11 compatible compilers (including mingw64) should provide

**Pull request merged**
