### PR TITLE
Minor corrections, typos

### PR DESCRIPTION
**Pull request by ak-dxdy**
These small corrections are also intended to try to understand git_openjpeg workflow.

### CODE REVIEW

**Comment by ak-dxdy** [comment]
I have done the following:
1) three commits;
2) pull request for them;
3) commit N 4 (stream...)

Now I view pull request, and I see all 4 commits. Is it normal?

**Comment by mayeut** [comment]
@ak-dxdy 
All commits on the same branch will appear in this PR

**Comment by mayeut** [comment]
I cherry picked 2 commits.
The one for jp2k contains too many formatting issues

**Comment by rouault** [comment]
It seems this PR has been (at least mostly) dealt with. @ak-dxdy  If there are remaining thins to fix, please re-open a new PR against current master.

**Pull request closed without merging**
