### PR TITLE
Support files with very large data size

### PR DESCRIPTION
**Pull request by stweil**
The maximum supported data size is a limiting factor for the maximum
size of allowed images. As it is possible to allocate size_t bytes,
this data type must also be used for the data size.

This modification also fixes issue #432. That file is now decoded on
64 bit hosts with enough RAM, so the regression test had to be fixed.

Update also some comments in the test suite.

Signed-off-by: Stefan Weil sw@weilnetz.de

### CODE REVIEW

**Comment by stweil** [comment]
The modified code in `tests/nonregression/test_suite.ctest.in` assumes a 64 bit host system (size_t > 32 bits) with enough RAM. Is it possible to use different test code for 32 bit hosts?

**Comment by stweil** [comment]
CI fails on some hosts when running the tests for issue #432. I think this must be fixed by updating the test code. As I am not familiar with `ctest`, I need help for this.
 
My test result is available here: http://my.cdash.org/buildSummary.php?buildid=933150

**Comment by stweil** [comment]
Updated PR, test for issue #432 is now temporarily disabled.

**Comment by stweil** [comment]
Ping? What is needed to get large file support integrated? The PR was now re-based on latest git version.

**Comment by mayeut** [comment]
@stweil, there are many places throughout the code where data is allocated with UINT32 size, or operations are performed on 32-bits size width * height.
To merge a PR for large images, all of those shall use size_t with proper overflow check when needed.
This is what I would expect. With no modification at all in bin folder, I doubt this will be properly working.

**Comment by stweil** [comment]
The limit which is addressed by this PR is width * height * 4 < 32 bit or width * height < 1073741824. I did not find more code with the same limit. Of course there are other code locations with different limitations, for example width * height < 32 bit. Maybe someone has a test image between those two limits, so we could test whether the new code works?

**Comment by jmichel-otb** [comment]
I recently ran into the same issue. Is there any way to move this forward ?

**Comment by stweil** [comment]
@jmichel-otb, the current question is whether this pull request alone is useful. There are code limitations which are not fixed here, so a general solution for large files needs more changes. If you have a valid example where this pull request helps, I think it will be applied. Maybe you can provide your example then for the test cases?

**Comment by jmichel-otb** [comment]
Well, what I can do is check if this branch fixes my problem. The test data is quite large (more than 4 Gb) and I think I can not give it away, but maybe I can generate a similar dataset. Nevertheless, I can also try to solve the other code limitations.

**Comment by stweil** [comment]
Checking would be great. Solving more code limitations would be even better. What are your image dimensions (width, height)?

**Comment by jmichel-otb** [comment]
I need to check because I do not have the image here, but it was roughly 40 000 x  160 000 pixels, so bigger than the width * height < 1073741824 limit.

**Comment by malaterre** [comment]
For the old timers, there used to be script for generating such images in SVN: https://groups.google.com/forum/#!msg/openjpeg/zGAIlZgxePE/Jx3L3y2u1kYJ

**Comment by stweil** [comment]
I rebased this pull request now to latest git master.

**Comment by stweil** [comment]
PR rebased again to fix merge conflicts.

**Comment by pedros007** [comment]
It would be great to have large file support for OpenJPEG!  

FWIW, I get a warning when building the `stweil:largefiles` branch via Docker with a debian:jessie base image:

```
git clone -b largefiles https://github.com/stweil/openjpeg.git /tmp/openjpeg
mkdir /tmp/openjpeg/build
cd /tmp/openjpeg/build
cmake .. -DCMAKE_INSTALL_PREFIX=/usr
make
```

```
[ 26%] Building C object src/lib/openjp2/CMakeFiles/openjp2.dir/tcd.c.o
/tmp/openjpeg/src/lib/openjp2/tcd.c: In function ‘opj_tcd_init_tile’:
/tmp/openjpeg/src/lib/openjp2/tcd.c:796:23: warning: conversion to ‘size_t’ from ‘OPJ_INT32’ may change the sign of the result [-Wsign-conversion]
         l_data_size = l_tilec->x1 - l_tilec->x0;
                       ^
/tmp/openjpeg/src/lib/openjp2/tcd.c:833:41: warning: conversion to ‘OPJ_UINT32’ from ‘size_t’ may alter its value [-Wconversion]
             l_tilec->resolutions_size = l_data_size;
                                         ^
/tmp/openjpeg/src/lib/openjp2/tcd.c:849:41: warning: conversion to ‘OPJ_UINT32’ from ‘size_t’ may alter its value [-Wconversion]
             l_tilec->resolutions_size = l_data_size;
                                         ^
/tmp/openjpeg/src/lib/openjp2/tcd.c: In function ‘opj_tcd_code_block_enc_allocate_data’:
/tmp/openjpeg/src/lib/openjp2/tcd.c:1191:70: warning: conversion to ‘long unsigned int’ from ‘OPJ_INT32’ may change the sign of the result [-Wsign-conversion]
                                (p_code_block->y1 - p_code_block->y0) * sizeof(OPJ_UINT32));
                                                                      ^
/tmp/openjpeg/src/lib/openjp2/tcd.c:1203:35: warning: conversion to ‘OPJ_UINT32’ from ‘size_t’ may alter its value [-Wconversion]
         p_code_block->data_size = l_data_size;
                                   ^
```

**Comment by stweil** [comment]
Pull request was rebased again, and warnings are fixed now.

**Comment by rouault** [comment]
This PR would only help for cases where number of pixels in tiles is < 4 billion. I'll integrate that, as well as other needed changes, in ongoing work for subtile decoding (not merging that right now to avoid merge conflicts)

**Comment by pedros007** [comment]
@rouault  are you talking about #1010? Sounds promising -- nice work!

**Comment by rouault** [comment]
@pedros007 Yes, exactly. This PR is included in https://github.com/uclouvain/openjpeg/pull/1010/commits/d5153ba404fa13b9c6e7b2c20d4d128aac718fba , https://github.com/uclouvain/openjpeg/pull/1010/commits/008a12d4fce0a7b1eabc51e04ed339be759646e2 and https://github.com/uclouvain/openjpeg/pull/1010/commits/98b93103613c90753fb6c57696f9403f8ea0b1d6 of #1010

**Comment by stweil** [comment]
Nice indeed, and good to see those improvements.

@rouault, maybe you can also replace the error message `Not enough memory for tile data` by `Size of tile data exceeds system limits`. There exist 32 bit systems which have more than 4 GiB RAM, but the system limit is nevertheless 32 bits.

**Comment by rouault** [comment]
https://github.com/uclouvain/openjpeg/pull/1010 has just been merged. This obsoletes this PR

**Pull request closed without merging**
