### PR TITLE
git commit -a

### PR DESCRIPTION
**Pull request by szukw000**

### CODE REVIEW

**Comment by detonin** [comment]
Hi Winfried. Thanks for submitting your flviewer. 
I see that there are different things in your pull request, in addition to flviewer: modifications to bin/jp2/convert.c and files in lib/openjp2/. 

Could you split your contributions according to their topic ? flviewer, bugfix in convert.c, other stuff, etc.
That would improve the readability of changes history ... Thanks !

**Comment by detonin** [comment]
Hi Winfried, do you intend to re-open a PR with flviewer only ?

**Comment by szukw000** [comment]
I am just working

 * on a patch for the library: jp2.c, src/bin/color.c, src/bin/jp2/opj_decompress.c
 * on a patch for flviewer: CMakeLists.txt, src/bin/CMakeLists.txt, fltk/flviewer

winfried

----- Original Nachricht ----
Von:     Antonin Descampe <notifications@github.com>
An:      uclouvain/openjpeg <openjpeg@noreply.github.com>
Datum:   23.06.2015 14:33
Betreff: Re: [openjpeg] git commit -a (#506)

**Comment by detonin** [comment]
ok great, thanks.

**Pull request closed without merging**
