### PR TITLE
CMake: error out on warnings for strict/missing prototypes.

### PR DESCRIPTION
**Pull request by sebras**
And fix strict-prototypes/missing-prototypes warnings.

### CODE REVIEW

**Comment by rouault** [comment]
@sebras errors for the mingw_64 target are at https://my.cdash.org/viewBuildError.php?buildid=2301396

**Comment by sebras** [comment]
> errors for the mingw_64 target are at https://my.cdash.org/viewBuildError.php?buildid=2301396

I know, I found them. I've fixed one of them, but the error relating to DllMain is puzzling to me (I'm mainly a Linux developer). :)

**Comment by rouault** [comment]
perhaps try the following change:
```
diff --git a/src/lib/openjp2/openjpeg.c b/src/lib/openjp2/openjpeg.c
index 29d3ee52..561e603d 100644
--- a/src/lib/openjp2/openjpeg.c
+++ b/src/lib/openjp2/openjpeg.c
@@ -33,6 +33,7 @@
 
 #ifdef _WIN32
 #include <windows.h>
+#include <process.h>
 #endif /* _WIN32 */
 
 #include "opj_includes.h"
```

**Comment by sebras** [comment]
I'll just follow the lead of cairo and declare DllMain locally in the file.
This _should_ avoid the warning/error, and I can't forsee that it would create any issues.

**Pull request merged**
