### PR TITLE
better -ffast-math handling

### PR DESCRIPTION
**Pull request by rdieter**
issue #488

See also
http://public.kitware.com/pipermail/cmake/2015-April/060479.html

### CODE REVIEW

**Comment by mayeut** [comment]
@rdieter,

Could you update your PR to include the same guards as in commit c5dd6035c942ab5969b7dc3a873e95e3b542f544 please ?

**Comment by malaterre** [comment]
I do not believe we handle this in openjpeg

**Comment by mayeut** [comment]
We do on master and now on branch openjpeg-1.5 after commit 650df81e09a3362010a4047e04313a24a4a687c8

**Comment by malaterre** [comment]
I believe that openjpeg lossless mode currenly only works with `-fexcess-precision=standard`

**Comment by mayeut** [comment]
Lossless tests are okay without `-fexcess-precision=standard` since #591 and #571 are fixed. Am I missing something ?

**Comment by malaterre** [comment]
That's precisely my point. OpenJPEG lossless code path was actually lossy until a couple of weeks back (project is > 10 yrs old!). So I am suggesting to be a little bit modest and do not pretend we handle those advanced options for now. If distro packager wants to use this flags then it is their responsabilities, that's fine.

**Comment by mayeut** [comment]
I understand your point. However this is another issue than the one taken care of here which used to mess with floating point configuration for people linking with openjpeg.

**Comment by malaterre** [comment]
point taken. sorry for the noise.

**Pull request closed without merging**
